### ISSUE TITLE
Setting allowFrame to true not working in Woofmark

### ISSUE THREAD

**Issue by jywarren** [bevacqua/domador#10]
I'm using `domador` within `woofmark` and my settings are as follows, but converting from wysiwyg mode back to HTML (which domador performs) is not preserving an `iFrame` (containing a YouTube video).

```js
domador(input, {
        allowFrame: true,
        inline: true,
        fencing:   true,
        fencinglanguage: function (el) {
          var match = el.className.match(/md-lang-((?:[^\s]|$)+)/);
          if (match) {
            return match.pop();
          }
        },
        transform: function (el) {

          if (el.tagName === 'A' && el.innerHTML[0] === '@') {
            return el.innerHTML;
          }

          if (el.tagName === 'A' && el.innerHTML[0] === '#') {
            return el.innerHTML;
          }

        }
      });
```

I also tried:

```js
        allowFrame: function(src) { return true },
```

But neither worked, with the markup:

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Ej_l1hANqMc" frameborder="0" allowfullscreen></iframe>
```

My code is in this branch: https://github.com/publiclab/PublicLab.Editor/pull/107/files#diff-a25f5d4b5c50e14d0bd66616d381892aR38205

**Comment by bevacqua** [comment]
@jywarren This works:

```bash
» node -e "console.log(require('./domador')('<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Ej_l1hANqMc\" frameborder=\"0\" allowfullscreen></iframe>',{allowFrame:()=>true}))"
<iframe src="https://www.youtube.com/embed/Ej_l1hANqMc"></iframe>
```

Thus, the issue is probably in that you're allowing frames on `domador` but then `woofmark` isn't configured to support YouTube iframes at the sanitizer level, and then they are stripped out. That would be my guess.

**Comment by jywarren** [comment]
@bevacqua - oh, thanks! I'll look through woofmark code but is this a configuration issue or a potential feature change that'd be required, if you know off the top of your head?

**Comment by jywarren** [comment]
Moving back to https://github.com/bevacqua/woofmark/issues/60 and closing this, @bevacqua's suggestion seems to work.
