### ISSUE TITLE
newlines in code blocks are eaten (w/ test)

### ISSUE THREAD

**Issue by jywarren** [bevacqua/domador#2]
Hi, great library -- I found a bug and wrote a test for it: https://github.com/jywarren/domador/commit/881cb3d18389b03b7e565dc7b28a1cc7c274dc65

`````` js
t.equal(domador('<p>foo</p><pre><code><span class="md-code-comment">// Code could go here</span>\n<span class="md-code-keyword">var</span> myVariable = <span class="md-code-number">4</span>;\n\n</code></pre>', { fencing: true }), 'foo\n\n```js\n\n// Code could go here\nvar myVariable = 4;\n\n```');
``````

Any hints on where I might be able to fix this? For reference, the HTML was generated by Megamark (in Woofmark) from the markdown provided in the test. Thanks!

**Comment by bevacqua** [comment]
Resolved in `2.4.0` via #3

Thanks!

**Comment by jywarren** [comment]
I'm sorry to be a pest -- I still get some newline errors for this test, even after rebasing it onto v2.4.0. I've been looking for where `span` elements inside of `code` elements are parsed, to add an additional `this.append('\n')`, but haven't figured it out yet. 

``````
not ok 24 should be equal
  ---
    operator: equal
    expected:
      'foo\n\n```js\n\n// Code could go here\nvar myVariable = 4;\n\n```'
    actual:
      'foo\n\n```\n// Code could go herevar myVariable = 4;\n\n```'
    at: Test.<anonymous> (/home/warren/sites/domador/test/domador.js:75:5)
  ...
``````

**Comment by jywarren** [comment]
I think the `span` elements are the cause. My test on top of 2.4.0: https://github.com/jywarren/domador/blob/code-fencing/test/domador.js#L75

**Comment by bevacqua** [comment]
Fixed that in `2.4.1`. Note that `\n{3,}` will still be collapsed to `\n\n` even when _inside_ code blocks. This is probably a non-issue (and I'm rather leaning towards "this is actually a feature")

**Comment by bevacqua** [comment]
Adding you as a collaborator to `domador`, `megamark`, and `woofmark`. Feel free to decline.

**Comment by jywarren** [comment]
OMG that's so great to hear. Green lights are turning on all over my downstream codebases :-)

Thanks, sounds good! Honored.
