### ISSUE TITLE
md-lang-javascript is scanned from pre but not code tags; opposite in megamark

### ISSUE THREAD

**Issue by jywarren** [bevacqua/domador#4]
One more -- sorry, i'm sure this is slightly annoying. 

Not sure whether to file this here or in [megamark](https://github.com/bevacqua/megamark), but megamark seems to insert the `md-lang-javascript` class into the `code` tags, not the `pre` tags, whereas domador reads only from the `pre` tags. (for purposes of the [fencinglanguage function](https://github.com/bevacqua/domador#fencinglanguage))

I'm going to try writing a test for this, and poking around the code a bit to see if I can simply extend this behavior to look in either `pre` or `code` tags.

**Comment by bevacqua** [comment]
Domador should probably try and read from both of them. Changing the HTML -> MD route is always going to be cheaper because that means we only change how we read HTML without modifying it

**Comment by jywarren** [comment]
Hmm, this one's a little tough, in terms of the relationship between nested tags. Looking for a way to search child tags from `pre`. 

OK, think i've gotten it in #5 -- thanks!

**Comment by bevacqua** [comment]
Fixed in `2.4.2`
